build: Chaine.o Reseau.o ReconstitueReseau.o
	gcc -o main Chaine.o Reseau.o ReconstitueReseau.o 

ReconstitueReseau.o:
	gcc -c ReconstitueReseau.c

Chaine.o:
	gcc -c Chaine.h Chaine.c

Reseau.o:
	gcc -c Reseau.h Reseau.c
